# Generated by Django 3.2 on 2025-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='凭据名称')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('auth_mode', models.IntegerField(choices=[(1, '秘钥'), (2, '密码')], default=1, verbose_name='认证方式')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, verbose_name='秘钥')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'system_config_credential',
                'ordering': ('-id',),
            },
        ),
    ]
