# Generated by Django 3.2 on 2025-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='auth_mode',
            field=models.IntegerField(choices=[(1, '密码'), (2, '秘钥')], default=1, verbose_name='认证方式'),
        ),
    ]
