# Generated by Django 3.2 on 2025-02-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_config', '0001_initial'),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system_config.credential', verbose_name='凭据'),
        ),
    ]
