# Generated by Django 3.2 on 2025-02-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_server_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='disk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='server',
            name='private_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公网IP'),
        ),
    ]
