# Generated by Django 3.2 on 2025-02-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20250224_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='is_verfied',
            new_name='is_verified',
        ),
    ]
